const INVALID_DATA_ERROR_CODE = 400;
const CAST_ERROR_CODE = 400;
const NOT_FOUND_ERROR_CODE = 404;
const INT_SERVER_ERROR_CODE = 500;
const AUTHORIZATION_ERROR_CODE = 401;

module.exports = {
  INVALID_DATA_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  INT_SERVER_ERROR_CODE,
  CAST_ERROR_CODE,
  AUTHORIZATION_ERROR_CODE
};
